[package]
name = "db_schema"
version = "0.1.0"
edition = "2024"

[dependencies]
diesel = { version = "2.3.6", features = ["postgres", "chrono", "serde_json"] }
serde = { version = "1.0.228", features = ["derive"] }
chrono = { version = "0.4.43", features = ["serde"] }
serde_json = "1.0.149"
